name: Terraform Deploy

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  terraform:
    name: Terraform Init/Plan/Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_USER_AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_USER_AWS_SECRET }}
      AWS_REGION: ap-south-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Import (VPC)
        run: terraform import aws_vpc.eks_vpc

      - name: Terraform Import (EKS Master Role)
        run: terraform import aws_iam_role.eks_master_role eks_masterrole

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform delete
        run: terraform apply -auto-approve
